Repository PrestaShop/ps_viewedproduct, pull requests merged in 2023-02, with the labels that each got.

#29 Adapt `ps_viewedproduct` for multiples versions of PrestaShop
  .github/workflows/php.yml
  ps_viewedproduct.php
  tests/phpstan/phpstan-1.7.1.2.neon
  tests/phpstan/phpstan-1.7.2.5.neon
  tests/phpstan/phpstan-1.7.3.4.neon
  tests/phpstan/phpstan-1.7.4.4.neon
  tests/phpstan/phpstan-8.0.neon
Labels: enhancement, QA ✔️

#30 Bump version to 1.2.4
  config.xml
  ps_viewedproduct.php
Labels: enhancement

#31 Release 1.2.4
  .github/workflows/php.yml
  config.xml
  ps_viewedproduct.php
  tests/phpstan/phpstan-1.7.1.2.neon
  tests/phpstan/phpstan-1.7.2.5.neon
  tests/phpstan/phpstan-1.7.3.4.neon
  tests/phpstan/phpstan-1.7.4.4.neon
  tests/phpstan/phpstan-8.0.neon
Labels: QA ✔️
